name: http_unit_test
description: A new Flutter project.
version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/http
  http: ^0.12.2
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/build_runner
  build_runner: ^1.11.1
  # https://pub.dev/packages/json_serializable
  json_serializable: ^3.5.1


flutter:
  uses-material-design: true