name: flutter_bloc_architecture
description: Demostrate the architecture of the app using flutter bloc
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/http
  http: ^0.12.2
  # https://pub.dev/packages/cached_network_image
  flutter_bloc: ^6.1.2
  # https://pub.dev/packages/equatable
  equatable: ^1.2.6
  # https://pub.dev/packages/url_launcher
  url_launcher: ^5.7.10
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/build_runner
  build_runner: ^1.11.1
  # https://pub.dev/packages/json_serializable
  json_serializable: ^3.5.1
  # https://pub.dev/packages/bloc_test
  bloc_test: ^7.1.0
  # https://pub.dev/packages/mockito
  mockito: ^4.1.4


flutter:
  uses-material-design: true